services:
  app:
    container_name: ${APP_NAME}
    build: .
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:15
    container_name: go_article_api_db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:${DOCKER_POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
  db-test:
    image: postgres:15
    environment:
      - POSTGRES_USER=${TEST_DB_USER}
      - POSTGRES_PASSWORD=${TEST_DB_PASSWORD}
      - POSTGRES_DB=${TEST_DB_NAME}
    ports:
      - "${TEST_DB_PORT}:${DOCKER_POSTGRES_PORT}"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d

volumes:
  postgres_data: